#!/bin/bash

# Special case for SOURCE_BRANCH build argument. If it's `master', change it to
# empty string so that the default value in Dockerfile works.

if [[ ${SOURCE_BRANCH} == "master" ]]
then
    export SOURCE_BRANCH=""
else
    export SOURCE_BRANCH=${SOURCE_BRANCH#v}
fi

echo "=> Overriding SOURCE_BRANCH to ${SOURCE_BRANCH}."

docker build --build-arg SOURCE_BRANCH=${SOURCE_BRANCH} \
    -f ${DOCKERFILE_PATH} -t ${IMAGE_NAME} .
